#ifndef MENU_H
#define MENU_H
#define MAX_CHARACTERS_FOR_OPTIONS 3

//FUNCION PARA DEVOLVER LA OPCION SELECCIONADA
int selectOpcion();

//FUNCION PARA IMPRIMIR EL MENU DE INICIO
int printMenuInicio();
//FUNCION PARA GESTION DEL MENU DE INICIO
void menuInicio();

//FUNCION PARA IMPRIMIR EL MENU PRINCIPAL
int printMenuPrincipal();
//FUNCION PARA GESTION DEL MENU PRINCIPAL
void menuPrincipal(char *usuario);

//FUNCION PARA MOSTRAR OPCIONES DE PERFIL
int printMenuPerfil();
//FUNCION PARA GESTION DEL MENU DE PERFIL
void menuPerfil();

void printMenuVerAct();


//FUNCION PARA MOSTRAR OPCIONES DE PERFIL
int printMenuLogin();
//FUNCION PARA GESTION DEL MENU DE LOGIN
void menuLogin();
//FUNCION PARA COMPROBAR SI LA OPCION INTRODUCIDA ES VALIDA
int comprobarOpcionValida(int opcion, int numOpciones);


#endif